# lsi: false
# safe: true
# source: /
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
full_rebuild: true
name: Learn Data Management
description: Website for educational resources pertaining to data management practices
destination: jekyllbuild
permalink: /:categories/:title/
paginate: 8
paginate_path: /page/:num/
infinite_scroll: true #change to false if you want to use pagination
plugins: [jekyll-paginate]
tag_dir: /tag
category_dir: /category
media_folder: /media/compressed

about: /about
resources: /resources

encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post-material-sidebar-right"
      type: "standard"
      homedisplay: "featimg"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
exclude: [.git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md, jekyllbuild]
